### ISSUE TITLE
Unofficial SpaceApps Challenge Forum - STEMN

### ISSUE THREAD

**Issue by joshleeb** [TeamNutBoltu/hypermate#1]
Hey HyperMate team,

We're a team from Sydney, Australia and we created a Pre-SpaceApps challenge to ourselves. We've created the unofficial Space Apps Challenge Forums! You can find them at https://stemn.com/org/sac.

We've added a project on STEMN for your HyperMate project. You can check it out here https://stemn.com/projects/hypermate. You can also check out all the discussions related to the Space Wearables theme in this thread: https://stemn.com/threads/transient-watch-%E2%80%93-daily-news-on-active-neutron-stars-and-black-holes-on-your-mobile-phone. Make sure you say hi in the thread so you can get to know the other teams in the theme.

To signup go to https://stemn.com/org/sac. We're currently in closed beta but have decided to give you special access with the signup code at that link. Once you've made an account, or if you have any questions, send me a email at josh@stemn.com and I can transfer the project to your account.

Goodluck this weekend.
See you on STEMN!

**Comment by toshazed** [comment]
It is very wrong to get our data and input them into any unofficial forum/site. We have released this project under MPL2.0 and you are in violation of it anyhow.
